[profile.default]
solc = '0.8.24'
evm_version='cancun'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    'seaport-core/=lib/seaport-core/',
    'seaport/=contracts/'
]
optimizer_runs = 9_999_999
fs_permissions = [
    { access = "read", path = "./optimized-out" },
    { access = "read", path = "./reference-out" },
    { access = "write", path = "./call-metrics.txt" },
    { access = "write", path = "./mutation-metrics.txt" },
    { access = "write", path = "./assume-metrics.txt" },
    { access = "write", path = "./fuzz_debug.json" }
]

[profile.validator]
solc = '0.8.17'
src = 'contracts/helpers/order-validator'
optimizer_runs = 1

[fuzz]
runs = 1_000
max_test_rejects = 1_000_000

[profile.reference]
solc = '0.8.24'
src = 'reference'
via_ir = false
out = 'reference-out'
script = 'reference'
test = 'test/foundry'
cache_path = 'reference-cache'


[profile.optimized]
via_ir = true
out = 'optimized-out'
script = 'contracts'
bytecode_hash = 'none'
# no need to compile tests with via-ir since they load optimized bytecode directly by default
test ='contracts'

[profile.test]
src = 'test/foundry'

[profile.test.fuzz]
runs = 1_000

[profile.lite]
out = 'optimized-out'

[profile.debug]
src = 'contracts'
optimizer = false

[profile.moat_debug]
optimizer = false
test = 'test/foundry/new'

[profile.offerers]
test='test/foundry/offerers'

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
[rpc_endpoints]
blastTest = "https://sepolia.blast.io"
blastMain = "https://rpc.blast.io"
baseTest = "https://sepolia.base.org"
baseMain = "https://mainnet.base.org"
ethTest = "https://rpc.sepolia.org"
ethMain = "https://eth-mainnet.public.blastapi.io"
flowMain = "https://mainnet.evm.nodes.onflow.org"

[etherscan]
blast_sepolia = { key = "${BLAST_API_KEY}" }
blast = { key = "${BLAST_API_KEY}" }
base_sepolia = { key = "${BASE_API_KEY}" }
base = { key = "${BASE_API_KEY}" }
sepolia = { key = "${ETHEREUM_API_KEY}" }
mainnet = { key = "${ETHEREUM_API_KEY}" }
flow = { key = "${FLOW_API_KEY}" }