[profile.default]
solc = '0.8.24'
src = 'contracts'
evm_version='cancun'
libs = ['lib']
fallback_oz = true
enable_eravm_extensions = false
is_system = false # Note: NonceHolder and the ContractDeployer system contracts can only be called with a special isSystem flag as true
optimizer_mode = "z"
via_ir = true
optimizer_runs = 9_999_999
bytecode_hash = 'none'
remappings = [
    '@rari-capital/solmate/=lib/solmate/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solarray/=lib/solarray/src/',
    'solady/=lib/solady/',
    'seaport-sol/=lib/seaport-sol/',
    'seaport-types/=lib/seaport-types/',
    "seaport/=lib/seaport/",
    "seaport-core/=lib/seaport-core/",
    'closedsea/=lib/closedsea/',
    'erc721a/=lib/closedsea/lib/erc721a'
]


[profile.optimized]
via_ir = true
out = 'optimized-out'
script = 'contracts'
bytecode_hash = 'none'
# no need to compile tests with via-ir since they load optimized bytecode directly by default
test ='contracts'

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
[rpc_endpoints]
blastTest = "https://sepolia.blast.io"
blastMain = "https://rpc.blast.io"
baseTest = "https://sepolia.base.org"
baseMain = "https://mainnet.base.org"
ethTest = "https://rpc.sepolia.org"
ethMain = "https://eth-mainnet.public.blastapi.io"
flowMain = "https://mainnet.evm.nodes.onflow.org"
apeMain = "https://apechain.calderachain.xyz/http"
abstractTest = "https://api.testnet.abs.xyz"
abstractMain = "https://api.mainnet.abs.xyz"
sophon = "${SOPHON_RPC_URL}"

[etherscan]
blast_sepolia = { key = "${BLAST_API_KEY}" }
blast = { key = "${BLAST_API_KEY}" }
base_sepolia = { key = "${BASE_API_KEY}" }
base = { key = "${BASE_API_KEY}" }
sepolia = { key = "${ETHEREUM_API_KEY}" }
mainnet = { key = "${ETHEREUM_API_KEY}" }
flow = { url = "https://evm.flowscan.io" , chain = 747, key = "${BASE_API_KEY}" }
apechain = { url = "https://api.apescan.io/api", chain = 33139 , key = "${APE_API_KEY}" }
abstract = { url = "https://api.abscan.org/api", chain = 2741, key = ''}
abstract_sepolia = { url = "https://api-sepolia.abscan.org/api", chain = 11124, key = ''}
sophon = { key = "4GSVF4EG37QD1V3ST61P82Y8Y88G62XPAZ", url = "${SOPHON_VERIFIER_URL}", chain = 50104 }
